create table users (
    id              bigint generated by default as identity primary key,
    email           varchar(254) unique,
    phone           varchar(20) unique,
    name            varchar(80),
    city            varchar(60),
    experience      varchar(20),
    trading_style   varchar(20),
    risk_appetite   varchar(20),
    capital         numeric(18, 2),
    risk_pct        numeric(6, 2),
    daily_loss_pct  numeric(6, 2),
    segments        varchar(200),
    start_view      varchar(20),
    board_city      varchar(60),
    news_mode       varchar(10),
    avatar          varchar(200000),
    totp_secret     varchar(64),
    totp_enabled    boolean not null default false,
    totp_last_step  bigint,
    created_at      timestamp with time zone not null,
    updated_at      timestamp with time zone not null
);

create table otp_challenges (
    id           bigint generated by default as identity primary key,
    destination  varchar(254) not null,
    code_hash    varchar(64) not null,
    attempts     int not null default 0,
    created_at   timestamp with time zone not null,
    expires_at   timestamp with time zone not null,
    used_at      timestamp with time zone
);
create index idx_otp_destination on otp_challenges (destination, created_at);

create table refresh_tokens (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users (id) on delete cascade,
    token_hash  varchar(64) not null unique,
    created_at  timestamp with time zone not null,
    expires_at  timestamp with time zone not null,
    revoked_at  timestamp with time zone
);
create index idx_refresh_user on refresh_tokens (user_id);

create table paper_positions (
    id           bigint generated by default as identity primary key,
    user_id      bigint not null references users (id) on delete cascade,
    kind         varchar(3) not null,
    symbol       varchar(40) not null,
    label        varchar(80) not null,
    side         varchar(1) not null,
    qty          numeric(20, 8),
    entry        numeric(18, 4) not null,
    stop         numeric(18, 4),
    target       numeric(18, 4),
    option_type  varchar(2),
    strike       numeric(12, 2),
    expiry       varchar(20),
    lots         int,
    lot_size     int,
    opened_at    timestamp with time zone not null,
    client_ref   varchar(40)
);
create index idx_positions_user on paper_positions (user_id);
create unique index uq_positions_client_ref on paper_positions (user_id, client_ref);

create table journal_entries (
    id          bigint generated by default as identity primary key,
    user_id     bigint not null references users (id) on delete cascade,
    symbol      varchar(40) not null,
    label       varchar(80) not null,
    side        varchar(1) not null,
    units       numeric(20, 8) not null,
    entry       numeric(18, 4) not null,
    exit_price  numeric(18, 4) not null,
    pnl         numeric(18, 2) not null,
    opened_at   timestamp with time zone not null,
    closed_at   timestamp with time zone not null,
    client_ref  varchar(40)
);
create index idx_journal_user on journal_entries (user_id, closed_at);
create unique index uq_journal_client_ref on journal_entries (user_id, client_ref);
